"""Finite-temperature susceptibility for a spin-1 chain using TeNPy purification.

The susceptibility per site is computed from zero-field fluctuations,

    chi(T) = beta / N * (<Mz^2> - <Mz>^2),

where Mz = sum_i Sz_i. The finite-temperature state is generated by applying
imaginary-time MPO evolution to a purification MPS, following TeNPy's
purification example.
"""

from __future__ import annotations

import argparse
import csv
from numbers import Integral, Real
from pathlib import Path

import numpy as np

from spin1_chain_dmrg import Spin1ChainWithSIA, Spin1ChainWithoutSIA


CSV_FIELDNAMES = [
    "case",
    "beta_meV_inv",
    "temperature_K",
    "chi_reduced_meV_inv",
    "chi_molar_m3_per_mol",
    "g_factor",
    "mz",
    "mz2",
    "n_sites",
]
CASE_PLOT_LABELS = {"with": "with SIA", "without": "without SIA"}

K_B_MEV_PER_K = 0.08617333262
MEV_TO_JOULE = 1.602176634e-22
VACUUM_PERMEABILITY = 1.25663706127e-6
AVOGADRO_CONSTANT = 6.02214076e23
BOHR_MAGNETON_J_PER_T = 9.2740100657e-24


def _validate_positive_integer(value: object, name: str) -> int:
    if isinstance(value, bool) or not isinstance(value, Integral) or value <= 0:
        raise ValueError(f"{name} must be a positive integer")
    return int(value)


def _validate_finite_real(value: object, name: str) -> float:
    if isinstance(value, bool) or not isinstance(value, Real) or not np.isfinite(value):
        raise ValueError(f"{name} must be a finite real number")
    return float(value)


def _validate_non_negative_real(value: object, name: str) -> float:
    value = _validate_finite_real(value, name)
    if value < 0.0:
        raise ValueError(f"{name} must be non-negative")
    return value


def _validate_positive_real(value: object, name: str) -> float:
    value = _validate_finite_real(value, name)
    if value <= 0.0:
        raise ValueError(f"{name} must be positive")
    return value


def beta_from_temperature_kelvin(temperature_k: float) -> float:
    temperature_k = _validate_positive_real(temperature_k, "temperature_k")
    return 1.0 / (K_B_MEV_PER_K * temperature_k)


def temperature_kelvin_from_beta(beta_mev_inv: float) -> float:
    beta_mev_inv = _validate_positive_real(beta_mev_inv, "beta_mev_inv")
    return 1.0 / (K_B_MEV_PER_K * beta_mev_inv)


def temperature_grid_kelvin(minimum_k: float, maximum_k: float, points: int) -> list[float]:
    minimum_k = _validate_positive_real(minimum_k, "minimum_k")
    maximum_k = _validate_positive_real(maximum_k, "maximum_k")
    points = _validate_positive_integer(points, "points")
    if maximum_k <= minimum_k:
        raise ValueError("maximum_k must be greater than minimum_k")
    if points < 2:
        raise ValueError("points must be at least 2")
    return [float(value) for value in np.geomspace(maximum_k, minimum_k, points)]


def reduced_susceptibility_from_moments(
    beta_mev_inv: float,
    n_sites: int,
    mz: float,
    mz2: float,
) -> float:
    beta_mev_inv = _validate_positive_real(beta_mev_inv, "beta_mev_inv")
    n_sites = _validate_positive_integer(n_sites, "n_sites")
    mz = _validate_finite_real(mz, "mz")
    mz2 = _validate_finite_real(mz2, "mz2")
    return beta_mev_inv * (mz2 - mz * mz) / n_sites


def molar_susceptibility_from_reduced(chi_reduced_mev_inv: float, g_factor: float) -> float:
    chi_reduced_mev_inv = _validate_finite_real(chi_reduced_mev_inv, "chi_reduced_mev_inv")
    g_factor = _validate_positive_real(g_factor, "g_factor")
    prefactor = (
        VACUUM_PERMEABILITY
        * AVOGADRO_CONSTANT
        * (g_factor * BOHR_MAGNETON_J_PER_T) ** 2
        / MEV_TO_JOULE
    )
    return prefactor * chi_reduced_mev_inv


def _validate_choice(value: object, name: str, choices: tuple[str, ...]) -> str:
    if not isinstance(value, str) or value not in choices:
        raise ValueError(f"{name} must be one of {choices}")
    return value


def magnetization_moments(psi) -> tuple[float, float]:
    """Return total <Mz> and <Mz^2> from a purification MPS."""
    mz = float(np.sum(psi.expectation_value("Sz")))
    mz2 = float(np.sum(psi.correlation_function("Sz", "Sz")))
    return mz, mz2


def susceptibility_from_moments(beta: float, n_sites: int, mz: float, mz2: float) -> float:
    """Return chi per site from total magnetization moments."""
    beta = _validate_non_negative_real(beta, "beta")
    n_sites = _validate_positive_integer(n_sites, "n_sites")
    mz = _validate_finite_real(mz, "mz")
    mz2 = _validate_finite_real(mz2, "mz2")
    if beta == 0.0:
        return 0.0
    return beta * (mz2 - mz * mz) / n_sites


def write_susceptibility_csv(rows: list[dict[str, float | int | str]], output_path: str | Path) -> None:
    """Write susceptibility rows with stable columns."""
    with Path(output_path).open("w", newline="", encoding="utf-8") as output:
        writer = csv.DictWriter(output, fieldnames=CSV_FIELDNAMES)
        writer.writeheader()
        writer.writerows(rows)


def _require_matplotlib_pyplot():
    try:
        import matplotlib

        matplotlib.use("Agg", force=True)
        import matplotlib.pyplot as plt
    except Exception as exc:
        raise RuntimeError(
            "Matplotlib is required to write the susceptibility plot. "
            "Install it with `python -m pip install matplotlib`."
        ) from exc
    return plt


def write_susceptibility_plot(
    rows: list[dict[str, float | int | str]],
    output_path: str | Path,
) -> None:
    plt = _require_matplotlib_pyplot()
    figure, axes = plt.subplots()
    cases = list(dict.fromkeys(str(row["case"]) for row in rows))
    for case in cases:
        points = sorted(
            (
                (float(row["temperature_K"]), float(row["chi_molar_m3_per_mol"]))
                for row in rows
                if row["case"] == case and np.isfinite(float(row["temperature_K"]))
            ),
            key=lambda point: point[0],
        )
        if not points:
            continue
        axes.plot(
            [point[0] for point in points],
            [point[1] for point in points],
            marker="o",
            markersize=3,
            label=CASE_PLOT_LABELS.get(case, case),
        )
    axes.set_xlabel("Temperature (K)")
    axes.set_ylabel("Molar susceptibility (m^3 mol^-1)")
    axes.ticklabel_format(axis="y", style="sci", scilimits=(0, 0))
    axes.grid(True, alpha=0.25)
    axes.legend()
    figure.tight_layout()
    figure.savefig(Path(output_path), dpi=300, bbox_inches="tight")
    plt.close(figure)


def _require_tenpy_purification():
    """Return TeNPy purification classes or explain how to run this script."""
    try:
        from tenpy.algorithms.purification import PurificationApplyMPO
        from tenpy.networks.purification_mps import PurificationMPS
    except Exception as exc:
        raise RuntimeError(
            "TeNPy purification is unavailable. Run this script from an installed "
            "TeNPy environment, for example after `python -m pip install -e .` in "
            "the cloned ritamcha/tenpy repository."
        ) from exc
    return PurificationApplyMPO, PurificationMPS


def _temperature_from_beta(beta: float) -> float:
    return float("inf") if beta == 0.0 else 1.0 / beta


def _measurement_row(
    case_label: str,
    beta_mev_inv: float,
    temperature_k: float,
    n_sites: int,
    psi,
    g_factor: float,
) -> dict[str, float | int | str]:
    mz, mz2 = magnetization_moments(psi)
    chi_reduced = reduced_susceptibility_from_moments(beta_mev_inv, n_sites, mz, mz2)
    return {
        "case": case_label,
        "beta_meV_inv": beta_mev_inv,
        "temperature_K": temperature_k,
        "chi_reduced_meV_inv": chi_reduced,
        "chi_molar_m3_per_mol": molar_susceptibility_from_reduced(chi_reduced, g_factor),
        "g_factor": g_factor,
        "mz": mz,
        "mz2": mz2,
        "n_sites": n_sites,
    }


def _mpo_propagators(tenpy_model, segment_dt: float) -> list[object]:
    return [
        tenpy_model.H_MPO.make_U(-step * segment_dt, "II")
        for step in (0.5 + 0.5j, 0.5 - 0.5j)
    ]


def run_case_scan(
    case_label: str,
    model,
    temperature_min_k: float,
    temperature_max_k: float,
    temperature_points: int,
    dt: float,
    chi_max: int,
    svd_min: float,
    g_factor: float,
) -> list[dict[str, float | int | str]]:
    """Cool one model from infinite temperature and return susceptibility rows."""
    _validate_choice(case_label, "case_label", ("with", "without"))
    temperatures = temperature_grid_kelvin(temperature_min_k, temperature_max_k, temperature_points)
    dt = _validate_positive_real(dt, "dt")
    chi_max = _validate_positive_integer(chi_max, "chi_max")
    svd_min = _validate_non_negative_real(svd_min, "svd_min")
    g_factor = _validate_positive_real(g_factor, "g_factor")

    PurificationApplyMPO, PurificationMPS = _require_tenpy_purification()
    tenpy_model = model.build_model()
    purification_kwargs = {"bc": tenpy_model.lat.bc_MPS}
    unit_cell_width = getattr(tenpy_model.lat, "mps_unit_cell_width", None)
    if unit_cell_width is not None:
        purification_kwargs["unit_cell_width"] = unit_cell_width
    psi = PurificationMPS.from_infiniteT(tenpy_model.lat.mps_sites(), **purification_kwargs)
    options = {"trunc_params": {"chi_max": chi_max, "svd_min": svd_min}}

    rows = []
    engine = None
    current_beta = 0.0
    for temperature_k in temperatures:
        target_beta = beta_from_temperature_kelvin(temperature_k)
        tolerance = 1.0e-12 * max(1.0, target_beta)
        while target_beta - current_beta > tolerance:
            beta_increment = min(2.0 * dt, target_beta - current_beta)
            segment_dt = 0.5 * beta_increment
            propagators = _mpo_propagators(tenpy_model, segment_dt)
            if engine is None:
                engine = PurificationApplyMPO(psi, propagators[0], options)
            for propagator in propagators:
                engine.init_env(propagator)
                engine.run()
            current_beta += beta_increment
        current_beta = target_beta
        rows.append(_measurement_row(
            case_label,
            target_beta,
            temperature_k,
            model.n_sites,
            psi,
            g_factor,
        ))

    rows.reverse()
    return rows


def _selected_cases(case: str) -> tuple[str, ...]:
    _validate_choice(case, "case", ("with", "without", "both"))
    if case == "both":
        return ("with", "without")
    return (case,)


def _build_case_model(case: str, n_sites: int, j_iso: float, dz: float, dpp: float, bc: str):
    if case == "with":
        return Spin1ChainWithSIA(n_sites=n_sites, j_iso=j_iso, dz=dz, dpp=dpp, bc=bc)
    if case == "without":
        return Spin1ChainWithoutSIA(n_sites=n_sites, j_iso=j_iso, bc=bc)
    raise ValueError("case must be one of ('with', 'without')")


def run_susceptibility_scan(
    case: str,
    n_sites: int,
    j_iso: float,
    dz: float,
    dpp: float,
    bc: str,
    temperature_min_k: float,
    temperature_max_k: float,
    temperature_points: int,
    dt: float,
    chi_max: int,
    svd_min: float,
    g_factor: float,
) -> list[dict[str, float | int | str]]:
    """Run the requested SIA case or cases and return all susceptibility rows."""
    n_sites = _validate_positive_integer(n_sites, "n_sites")
    j_iso = _validate_finite_real(j_iso, "j_iso")
    dz = _validate_finite_real(dz, "dz")
    dpp = _validate_finite_real(dpp, "dpp")
    bc = _validate_choice(bc, "bc", ("open", "periodic"))
    temperature_grid_kelvin(temperature_min_k, temperature_max_k, temperature_points)
    dt = _validate_positive_real(dt, "dt")
    chi_max = _validate_positive_integer(chi_max, "chi_max")
    svd_min = _validate_non_negative_real(svd_min, "svd_min")
    g_factor = _validate_positive_real(g_factor, "g_factor")

    rows = []
    for selected_case in _selected_cases(case):
        model = _build_case_model(selected_case, n_sites, j_iso, dz, dpp, bc)
        rows.extend(run_case_scan(
            selected_case,
            model,
            temperature_min_k,
            temperature_max_k,
            temperature_points,
            dt,
            chi_max,
            svd_min,
            g_factor,
        ))
    return rows


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--n-sites", type=int, default=12, help="Number of spin-1 sites.")
    parser.add_argument("--j", type=float, default=-16.1, help="J in H = -2 J sum_i S_i.S_{i+1}.")
    parser.add_argument("--dz", type=float, default=0.379, help="Coefficient Dz for sum_i (Sz_i)^2.")
    parser.add_argument(
        "--dpp",
        type=float,
        default=-0.017,
        help="Coefficient Dpp for sum_i [(Sp_i)^2 + (Sm_i)^2].",
    )
    parser.add_argument("--bc", choices=("open", "periodic"), default="open", help="Lattice boundary condition.")
    parser.add_argument("--case", choices=("with", "without", "both"), default="with")
    parser.add_argument("--temperature-min-k", type=float, default=None, help="Minimum temperature in K.")
    parser.add_argument("--temperature-max-k", type=float, default=1200.0, help="Maximum temperature in K.")
    parser.add_argument("--temperature-points", type=int, default=150, help="Number of logarithmic temperatures.")
    parser.add_argument(
        "--beta-max",
        type=float,
        default=None,
        help="Deprecated alternative to --temperature-min-k, in meV^-1.",
    )
    parser.add_argument(
        "--dt",
        type=float,
        default=0.01,
        help="Maximum purification half-step in meV^-1.",
    )
    parser.add_argument("--g-factor", type=float, default=2.0, help="Lande g-factor along z.")
    parser.add_argument("--chi-max", type=int, default=100, help="Maximum purification bond dimension.")
    parser.add_argument("--svd-min", type=float, default=1.0e-8, help="Minimum singular value retained.")
    parser.add_argument(
        "--csv",
        default="spin1_chain_susceptibility_vs_temperature.csv",
        help="Output CSV path.",
    )
    parser.add_argument(
        "--plot",
        default="spin1_chain_susceptibility_vs_temperature.png",
        help="Output PNG path.",
    )
    args = parser.parse_args(argv)
    if args.temperature_min_k is not None and args.beta_max is not None:
        parser.error("--temperature-min-k cannot be combined with --beta-max")
    if args.temperature_min_k is None:
        if args.beta_max is None:
            args.temperature_min_k = 2.0
        else:
            try:
                args.temperature_min_k = temperature_kelvin_from_beta(args.beta_max)
            except ValueError as exc:
                parser.error(str(exc))
    return args


def main(argv: list[str] | None = None) -> None:
    args = parse_args(argv)
    rows = run_susceptibility_scan(
        case=args.case,
        n_sites=args.n_sites,
        j_iso=args.j,
        dz=args.dz,
        dpp=args.dpp,
        bc=args.bc,
        temperature_min_k=args.temperature_min_k,
        temperature_max_k=args.temperature_max_k,
        temperature_points=args.temperature_points,
        dt=args.dt,
        chi_max=args.chi_max,
        svd_min=args.svd_min,
        g_factor=args.g_factor,
    )
    write_susceptibility_csv(rows, args.csv)
    write_susceptibility_plot(rows, args.plot)
    print(f"Wrote {args.csv}")
    print(f"Wrote {args.plot}")


if __name__ == "__main__":
    main()
